spring.application.name=patupi

# Database Connection (Translated from your Supabase String)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ydobyxgnnxpjyuuzzqod
spring.datasource.password=bomboclategg123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'none' ensures Spring doesn't try to overwrite your Supabase tables
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Disable default security login for now so we can test endpoints
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration